### ISSUE TITLE
EPG: Specific Program Detail doen't export json

### ISSUE THREAD

**Issue by biafra** [nosinovacao/pixelscamp#2]
Using the example:

$ curl -XGET "http://nos-brpx.northeurope.cloudapp.azure.com/EPGRepositories/EPGCatalog.svc/Program('1395116')?$format=json"

<?xml version="1.0" encoding="utf-8"?><entry xml:base="http://nos-brpx.northeurope.cloudapp.azure.com/EPGRepositories/EPGCatalog.svc/" xmlns="http://www.w3.org/2005/Atom" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:georss="http://www.georss.org/georss" xmlns:gml="http://www.opengis.net/gml"><id>http://nos-brpx.northeurope.cloudapp.azure.com/EPGRepositories/EPGCatalog.svc/Program('1395116')</id><category term="ZON.EPG.Catalog.Server.OData.Model.Program" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" /><link rel="edit" title="Program" href="Program('1395116')" /><title /><updated>2016-10-06T12:41:32Z</updated><author><name /></author><content type="application/xml"><m:properties><d:ProgramId>1395116/d:ProgramId<d:ActorsDisplay>Kevin Bacon,Natalie Zea,Annie Parisse/d:ActorsDisplay<d:Description>Com o seu maior alvo em fuga, Ryan e Mike seguem uma pista até uma pequena cidade. Aí, descobrem uma ameaça ainda maior que não levantara suspeitas até então. Enquanto isso, Max tem dificuldades em fazer uma confissão./d:Description<d:DirectorsDisplay>Kevin Williamson/d:DirectorsDisplay<d:Episode m:type="Edm.Int32">6/d:Episode<d:ExtendedProperties m:type="Collection(ZON.EPG.Catalog.Server.OData.Model.ExtendedProperty)" /><d:GenresDisplay>Séries/d:GenresDisplay<d:Rating>M3/d:Rating<d:RatingCode>1/d:RatingCode<d:RatingImdb>7,5/d:RatingImdb<d:GroupId m:type="Edm.Int32">2539703/d:GroupId<d:GroupImageUri m:null="true" /><d:GroupImageFile m:null="true" /><d:Season m:type="Edm.Int32">3/d:Season<d:SeriesId m:type="Edm.Int32">25397/d:SeriesId<d:Subtitle>Reunion/d:Subtitle<d:Title>Os Seguidores/d:Title<d:UniqueId m:null="true" /><d:Year>2013/d:Year<d:OriginalTitle>The Following/d:OriginalTitle<d:OriginalSubTitle>/d:OriginalSubTitle<d:IsPremiere>False/d:IsPremiere<d:IsFeatured>False/d:IsFeatured<d:MetadataTag m:type="ZON.EPG.Catalog.Server.OData.Model.Tag"><d:Id>416105f3-da8b-4585-8633-67969ab653b3/d:Id<d:DisplayName m:null="true" /><d:BeginTimeSpan m:type="Edm.Time">PT0S/d:BeginTimeSpan<d:EndTimeSpan m:type="Edm.Time">PT0S/d:EndTimeSpan/d:MetadataTag<d:Actors m:type="Collection(Edm.String)"><d:element>Kevin Bacon/d:element<d:element>Natalie Zea/d:element<d:element>Annie Parisse/d:element/d:Actors<d:Directors m:type="Collection(Edm.String)"><d:element>Kevin Williamson/d:element/d:Directors/m:properties</content></entry>

**Comment by ctorrao** [comment]
Maybe you missed the escape char for the "$" ?

The correct invocation should be:

``` bash
$ curl -XGET "http://nos-brpx.northeurope.cloudapp.azure.com/EPGRepositories/EPGCatalog.svc/Program('1395116')?\$format=json"
```

Does it work for you?

If not you can also add the HTTP Header "Accept: application/json" in all requests

**Comment by biafra** [comment]
Great, it works that way. But all the other examples worked without
escaping it :-)

It works smoothly with %24format=json also.

Thank you!

2016-10-06 13:57 GMT+01:00 Carlos Torrão notifications@github.com:

**Comment by ctorrao** [comment]
Great! Closed!
